site_name: Ploopy Adept Trackball
site_url: https://ploopyco.github.io/adept-trackball
theme: material
nav:
  - 'index.md'
  - 'assembly-instructions.md'
  - Appendices:
    - 'appendices/pcbs.md'
    - 'appendices/3d-printing.md'
    - 'appendices/hardware.md'
    - 'appendices/programming.md'
  - 'license.md'
